{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "ename": "ModuleNotFoundError",
     "evalue": "No module named 'pandas'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mModuleNotFoundError\u001b[0m                       Traceback (most recent call last)",
      "\u001b[0;32m/tmp/ipykernel_22759/2954115482.py\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mimport\u001b[0m \u001b[0mpandas\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mnetworkx\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mnx\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mmatplotlib\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mpyplot\u001b[0m \u001b[0;32mas\u001b[0m \u001b[0mplt\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0;32mimport\u001b[0m \u001b[0mrandom\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mModuleNotFoundError\u001b[0m: No module named 'pandas'"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import networkx as nx\n",
    "import matplotlib.pyplot as plt\n",
    "\n",
    "import random\n",
    "import itertools\n",
    "from pprint import pprint"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "def intOrEmpty(x):\n",
    "    try:\n",
    "        return int(x)\n",
    "    except Exception as e:\n",
    "        return \"\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [
    {
     "ename": "FileNotFoundError",
     "evalue": "[Errno 2] No such file or directory: '.cache/nokdb/nokdb-persons.csv'",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mFileNotFoundError\u001b[0m                         Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-3-2a1babf065f4>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mpersons_df\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_csv\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\".cache/nokdb/nokdb-persons.csv\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mpersons_df\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"father_pid\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpersons_df\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"father_pid\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mintOrEmpty\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      3\u001b[0m \u001b[0mpersons_df\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"mother_pid\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpersons_df\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"mother_pid\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmap\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mintOrEmpty\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      4\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m \u001b[0mimages_df\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mread_csv\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\".cache/nokdb/nokdb-images.csv\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/diploma/lib/python3.6/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36mread_csv\u001b[0;34m(filepath_or_buffer, sep, delimiter, header, names, index_col, usecols, squeeze, prefix, mangle_dupe_cols, dtype, engine, converters, true_values, false_values, skipinitialspace, skiprows, skipfooter, nrows, na_values, keep_default_na, na_filter, verbose, skip_blank_lines, parse_dates, infer_datetime_format, keep_date_col, date_parser, dayfirst, cache_dates, iterator, chunksize, compression, thousands, decimal, lineterminator, quotechar, quoting, doublequote, escapechar, comment, encoding, dialect, error_bad_lines, warn_bad_lines, delim_whitespace, low_memory, memory_map, float_precision)\u001b[0m\n\u001b[1;32m    686\u001b[0m     )\n\u001b[1;32m    687\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 688\u001b[0;31m     \u001b[0;32mreturn\u001b[0m \u001b[0m_read\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfilepath_or_buffer\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    689\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    690\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/diploma/lib/python3.6/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m_read\u001b[0;34m(filepath_or_buffer, kwds)\u001b[0m\n\u001b[1;32m    452\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    453\u001b[0m     \u001b[0;31m# Create the parser.\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 454\u001b[0;31m     \u001b[0mparser\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mTextFileReader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mfp_or_buf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    455\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    456\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mchunksize\u001b[0m \u001b[0;32mor\u001b[0m \u001b[0miterator\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/diploma/lib/python3.6/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, f, engine, **kwds)\u001b[0m\n\u001b[1;32m    946\u001b[0m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptions\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"has_index_names\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mkwds\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"has_index_names\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    947\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m--> 948\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_make_engine\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mengine\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m    949\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m    950\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0mclose\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/diploma/lib/python3.6/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m_make_engine\u001b[0;34m(self, engine)\u001b[0m\n\u001b[1;32m   1178\u001b[0m     \u001b[0;32mdef\u001b[0m \u001b[0m_make_engine\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mengine\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"c\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1179\u001b[0m         \u001b[0;32mif\u001b[0m \u001b[0mengine\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"c\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 1180\u001b[0;31m             \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_engine\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mCParserWrapper\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mf\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0moptions\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   1181\u001b[0m         \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   1182\u001b[0m             \u001b[0;32mif\u001b[0m \u001b[0mengine\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;34m\"python\"\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32m~/anaconda3/envs/diploma/lib/python3.6/site-packages/pandas/io/parsers.py\u001b[0m in \u001b[0;36m__init__\u001b[0;34m(self, src, **kwds)\u001b[0m\n\u001b[1;32m   2008\u001b[0m         \u001b[0mkwds\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"usecols\"\u001b[0m\u001b[0;34m]\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0musecols\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2009\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m-> 2010\u001b[0;31m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_reader\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mparsers\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mTextReader\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0msrc\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;34m**\u001b[0m\u001b[0mkwds\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m   2011\u001b[0m         \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munnamed_cols\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mself\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0m_reader\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0munnamed_cols\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m   2012\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;32mpandas/_libs/parsers.pyx\u001b[0m in \u001b[0;36mpandas._libs.parsers.TextReader.__cinit__\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;32mpandas/_libs/parsers.pyx\u001b[0m in \u001b[0;36mpandas._libs.parsers.TextReader._setup_parser_source\u001b[0;34m()\u001b[0m\n",
      "\u001b[0;31mFileNotFoundError\u001b[0m: [Errno 2] No such file or directory: '.cache/nokdb/nokdb-persons.csv'"
     ]
    }
   ],
   "source": [
    "persons_df = pd.read_csv(\".cache/nokdb/nokdb-persons.csv\")\n",
    "persons_df[\"father_pid\"] = persons_df[\"father_pid\"].map(intOrEmpty)\n",
    "persons_df[\"mother_pid\"] = persons_df[\"mother_pid\"].map(intOrEmpty)\n",
    "\n",
    "images_df = pd.read_csv(\".cache/nokdb/nokdb-images.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name 'images_df' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[0;31m---------------------------------------------------------------------------\u001b[0m",
      "\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)",
      "\u001b[0;32m<ipython-input-4-f2f65b8327c6>\u001b[0m in \u001b[0;36m<module>\u001b[0;34m\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mimages_per_person_df\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mimages_df\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mgroupby\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"pid\"\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mas_index\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;32mFalse\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m[\u001b[0m\u001b[0;34m\"iid\"\u001b[0m\u001b[0;34m]\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mcount\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mrename\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mcolumns\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m{\u001b[0m\u001b[0;34m\"iid\"\u001b[0m\u001b[0;34m:\u001b[0m \u001b[0;34m\"n_images\"\u001b[0m\u001b[0;34m}\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      2\u001b[0m \u001b[0mpersons_df\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0mpd\u001b[0m\u001b[0;34m.\u001b[0m\u001b[0mmerge\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mpersons_df\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mimages_per_person_df\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mon\u001b[0m\u001b[0;34m=\u001b[0m\u001b[0;34m\"pid\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n",
      "\u001b[0;31mNameError\u001b[0m: name 'images_df' is not defined"
     ]
    }
   ],
   "source": [
    "images_per_person_df = images_df.groupby(\"pid\", as_index=False)[\"iid\"].count().rename(columns={\"iid\": \"n_images\"})\n",
    "persons_df = pd.merge(persons_df, images_per_person_df, on=\"pid\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "persons_df.head()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "G = nx.DiGraph()\n",
    "\n",
    "# Add nodes\n",
    "for index, row in persons_df.iterrows():\n",
    "    G.add_node(int(row[\"pid\"]), sex=row[\"sex\"], n_images=row[\"n_images\"], name=row[\"name\"], pid=int(row[\"pid\"]))\n",
    "\n",
    "# Add edges\n",
    "for index, row in persons_df.iterrows():\n",
    "    if row[\"father_pid\"]:\n",
    "        G.add_edge(int(row[\"father_pid\"]), int(row[\"pid\"]))\n",
    "    if row[\"mother_pid\"]:\n",
    "        G.add_edge(int(row[\"mother_pid\"]), int(row[\"pid\"]))\n",
    "\n",
    "# Remove nodes without data\n",
    "for n in [n for n, data in G.nodes(data=True) if \"name\" not in data or \"sex\" not in data or \"n_images\" not in data or \"pid\" not in data]:\n",
    "    G.remove_node(n)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "def keep_only_full_families(G):\n",
    "    G = G.copy()\n",
    "\n",
    "    prev = (0, 0)\n",
    "    curr = (len(G.nodes()), len(G.edges()))\n",
    "    if (prev != curr):\n",
    "        # remove parent-child relation if child don't have both parents\n",
    "        for e in [e for e in G.edges() if len(G.in_edges(e[1])) == 1]:\n",
    "            G.remove_edge(*e)\n",
    "        \n",
    "        # remove nodes withot relation\n",
    "        for n in [n for n in G.nodes() if len(G.in_edges(n)) + len(G.out_edges(n)) == 0]:\n",
    "            G.remove_node(n)\n",
    "\n",
    "        prev = curr\n",
    "        curr = (len(G.nodes()), len(G.edges()))\n",
    "\n",
    "    return G\n",
    "\n",
    "def count_triplets(G):\n",
    "    fms = 0\n",
    "    fmd = 0\n",
    "    for n, data in [(n, data) for n, data in G.nodes(data=True) if len(G.in_edges(n)) == 2]:\n",
    "        if data[\"sex\"] == \"M\":\n",
    "            fms += 1\n",
    "        else:\n",
    "            fmd += 1\n",
    "    return fms, fmd\n",
    "\n",
    "def remove_less_represented_nodes(G, lim=1):\n",
    "    G = keep_only_full_families(G)\n",
    "    for n in [n for n, data in G.nodes(data=True) if data[\"n_images\"] < lim]:\n",
    "        G.remove_node(n)\n",
    "    G = keep_only_full_families(G)\n",
    "\n",
    "    return G\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "families = [\n",
    "    (1, count_triplets(remove_less_represented_nodes(G, 1))),\n",
    "    (2, count_triplets(remove_less_represented_nodes(G, 2))),\n",
    "    (3, count_triplets(remove_less_represented_nodes(G, 3))),\n",
    "    (4, count_triplets(remove_less_represented_nodes(G, 4))),\n",
    "    (5, count_triplets(remove_less_represented_nodes(G, 5))),\n",
    "    (6, count_triplets(remove_less_represented_nodes(G, 6))),\n",
    "]\n",
    "\n",
    "families"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "for lim, (fms, fmd) in families:\n",
    "    plt.bar(lim, fms,               label=\"Father-Mother-Son\" if lim == 1 else \"_nolegend_\", color=\"tab:blue\")\n",
    "    plt.bar(lim, fmd, bottom=fms,   label=\"Father-Mother-Daughter\" if lim == 1 else \"_nolegend_\", color=\"tab:pink\")\n",
    "\n",
    "plt.title(\"Number of triplets\")\n",
    "plt.ylabel(\"Count\")\n",
    "plt.xlabel(\"Limit\")\n",
    "plt.legend()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "def plot_graph(G, pdf_file_path):\n",
    "    COLOR_MALE = \"#34aeeb\"\n",
    "    COLOR_FEMALE = \"#de3e7e\"\n",
    "\n",
    "    node_colors = [COLOR_MALE if n[1][\"sex\"] == \"M\" else COLOR_FEMALE for n in G.nodes(data=True)]\n",
    "    pos = nx.drawing.nx_agraph.graphviz_layout(G, prog='dot')\n",
    "    labels = {n[0]: f\"{n[0]}\\n{n[1]['name']}\" for n in G.nodes(data=True)}\n",
    "\n",
    "    plt.clf()\n",
    "    plt.figure(num=None, figsize=(200, 1.5), frameon=False, clear=True, tight_layout=True)\n",
    "\n",
    "    nx.draw_networkx_nodes(G, pos=pos, node_color=node_colors, node_size=50, linewidths=0.0, alpha=0.5)\n",
    "    nx.draw_networkx_edges(G, pos=pos, node_size=50, width=0.1, arrowsize=5, style=\"dashed\", alpha=1)\n",
    "    nx.draw_networkx_labels(G, pos=pos, labels=labels, font_size=2)\n",
    "\n",
    "    plt.tight_layout()\n",
    "    plt.savefig(pdf_file_path, format=\"pdf\", orientation=\"landscape\")\n",
    "    plt.close()"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "# plot_graph(remove_less_represented_nodes(G, 1), \"kin-trees-1.pdf\")\n",
    "# plot_graph(remove_less_represented_nodes(G, 5), \"kin-trees-5.pdf\")"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Split to train and test dataset\n",
    "\n",
    "We will use graph connected components to split the dataset"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "Gx = remove_less_represented_nodes(G, 5)\n",
    "components = list(nx.connected_components(Gx.to_undirected()))\n",
    "\n",
    "test_i  = set(random.sample(range(len(components)), int(len(components)*0.1)))\n",
    "val_i   = set(random.sample(set(range(len(components))) - test_i, int(len(components)*0.1)))\n",
    "train_i = set(range(len(components))) - test_i - val_i\n",
    "\n",
    "train_pids  = set().union(*[components[i] for i in train_i])\n",
    "val_pids    = set().union(*[components[i] for i in val_i])\n",
    "test_pids   = set().union(*[components[i] for i in test_i])\n",
    "\n",
    "\n",
    "train_samples = []\n",
    "val_samples =   []\n",
    "test_samples =  []\n",
    "for n, data in Gx.nodes(data=True):\n",
    "    if(len(Gx.in_edges(n)) != 2): continue\n",
    "\n",
    "    parents = list(map(lambda x: x[0], Gx.in_edges(n)))\n",
    "    p1 = Gx.nodes[parents[0]]\n",
    "    p2 = Gx.nodes[parents[1]]\n",
    "\n",
    "    is_train = n in train_pids\n",
    "    is_val   = n in val_pids\n",
    "\n",
    "    c_pid = n\n",
    "    f_pid = None\n",
    "    m_pid = None\n",
    "    if p1[\"sex\"] == \"M\":\n",
    "        f_pid = p1[\"pid\"]\n",
    "        m_pid = p2[\"pid\"]\n",
    "    else:\n",
    "        f_pid = p2[\"pid\"]\n",
    "        m_pid = p1[\"pid\"]\n",
    "\n",
    "    f_iids = list(map(lambda x: (f_pid, x), images_df[images_df[\"pid\"] == f_pid][\"iid\"].tolist()))\n",
    "    m_iids = list(map(lambda x: (m_pid, x), images_df[images_df[\"pid\"] == m_pid][\"iid\"].tolist()))\n",
    "    c_iids = list(map(lambda x: (c_pid, x), images_df[images_df[\"pid\"] == c_pid][\"iid\"].tolist()))\n",
    "    \n",
    "    new_samples = list(map(\n",
    "        lambda x: [x[0][0], x[0][1], x[1][0], x[1][1], x[2][0], x[2][1]],\n",
    "        itertools.product(f_iids, m_iids, c_iids)\n",
    "    ))\n",
    "    \n",
    "    if is_train:\n",
    "        train_samples += new_samples\n",
    "    elif is_val:\n",
    "        val_samples += new_samples\n",
    "    else:\n",
    "        test_samples += new_samples\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [
    {
     "ename": "",
     "evalue": "",
     "output_type": "error",
     "traceback": [
      "\u001b[1;31mFailed to start the Kernel. \n",
      "Traceback (most recent call last):\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/daemon/daemon_python.py\", line 54, in _decorator\n",
      "    return func(self, *args, **kwargs)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 108, in m_exec_module_observable\n",
      "    self._start_notebook(args, cwd, env)\n",
      "  File \"/home/potocnikvid/.vscode/extensions/ms-toolsai.jupyter-2022.3.1000901801/pythonFiles/vscode_datascience_helpers/jupyter_daemon.py\", line 154, in _start_notebook\n",
      "    from notebook import notebookapp as app\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/notebookapp.py\", line 80, in <module>\n",
      "    from .services.contents.manager import ContentsManager\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/notebook/services/contents/manager.py\", line 17, in <module>\n",
      "    from nbformat import sign, validate as validate_nb, ValidationError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/__init__.py\", line 11, in <module>\n",
      "    from . import v1, v2, v3, v4\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/__init__.py\", line 39, in <module>\n",
      "    from .convert import downgrade, upgrade\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/v4/convert.py\", line 13, in <module>\n",
      "    from .. import validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/validator.py\", line 13, in <module>\n",
      "    from .json_compat import ValidationError, _validator_for_name, get_current_validator\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/nbformat/json_compat.py\", line 11, in <module>\n",
      "    import jsonschema\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/__init__.py\", line 12, in <module>\n",
      "    from jsonschema._format import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_format.py\", line 10, in <module>\n",
      "    from jsonschema.exceptions import FormatError\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/exceptions.py\", line 13, in <module>\n",
      "    from jsonschema import _utils\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/jsonschema/_utils.py\", line 12, in <module>\n",
      "    import importlib_resources as resources  # type: ignore\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/__init__.py\", line 3, in <module>\n",
      "    from ._common import (\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_common.py\", line 10, in <module>\n",
      "    from .abc import ResourceReader, Traversable\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/abc.py\", line 5, in <module>\n",
      "    from ._compat import runtime_checkable, Protocol, StrPath\n",
      "  File \"/home/potocnikvid/.local/lib/python3.8/site-packages/importlib_resources/_compat.py\", line 14, in <module>\n",
      "    from zipp import Path as ZipPath  # type: ignore\n",
      "ImportError: cannot import name 'Path' from 'zipp' (/home/potocnikvid/.local/lib/python3.8/site-packages/zipp.py)\n",
      "\n",
      "Failed to run jupyter as observable with args notebook --no-browser --notebook-dir=\"/home/potocnikvid/Documents/FRI/fri-2021-masters-main-master\" --KernelManager.autorestart=False --config=/tmp/8b209855-c9a4-4b95-a273-81bd60d212fd/jupyter_notebook_config.py --NotebookApp.iopub_data_rate_limit=10000000000.0. \n",
      "View Jupyter <a href='command:jupyter.viewOutput'>log</a> for further details."
     ]
    }
   ],
   "source": [
    "pd.DataFrame.from_records(train_samples, columns=[\"f_pid\", \"f_iid\", \"m_pid\", \"m_iid\", \"c_pid\", \"c_iid\"]).to_csv(\"dataset/nokdb-samples-al5-train.csv\", index=False)\n",
    "\n",
    "pd.DataFrame.from_records(val_samples , columns=[\"f_pid\", \"f_iid\", \"m_pid\", \"m_iid\", \"c_pid\", \"c_iid\"]).to_csv(\"dataset/nokdb-samples-al5-validation.csv\", index=False)\n",
    "\n",
    "pd.DataFrame.from_records(test_samples , columns=[\"f_pid\", \"f_iid\", \"m_pid\", \"m_iid\", \"c_pid\", \"c_iid\"]).to_csv(\"dataset/nokdb-samples-al5-test.csv\", index=False)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.5"
  },
  "metadata": {
   "interpreter": {
    "hash": "2ca3a44b8209f7ad007e433b11a4146eceddfdad5cdb64f89eb05e06944554d2"
   }
  },
  "orig_nbformat": 2,
  "vscode": {
   "interpreter": {
    "hash": "767d51c1340bd893661ea55ea3124f6de3c7a262a8b4abca0554b478b1e2ff90"
   }
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
